
string(TOLOWER ${CMAKE_HOST_SYSTEM_NAME} BUILD_HOST)

list(PREPEND CMAKE_BUILD_RPATH ".")
set(LIB_EXT "so")
set(INSTALL_TEST OFF)
set(PNG_TESTS OFF)
set(PNG_EXECUTABLES OFF)
set(PNG_SHARED OFF)
set(PNG_STATIC ON)
